# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchGoer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('maiden_name', models.CharField(max_length=255)),
                ('nickname', models.CharField(blank=True, max_length=255)),
                ('birthday', models.DateTimeField(blank=True)),
                ('name_of_guardian', models.CharField(max_length=750)),
                ('home_church', models.CharField(blank=True, max_length=500)),
                ('family_are_beargrass_members', models.BooleanField()),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('school', models.CharField(blank=True, max_length=500)),
                ('degree', models.TextField(blank=True)),
                ('employer', models.CharField(blank=True, max_length=500)),
                ('gender', models.CharField(max_length=3)),
                ('facebook_URL', models.URLField(blank=True)),
                ('google_plus_URL', models.URLField(blank=True)),
                ('instagram_URL', models.URLField(blank=True)),
                ('snapchat_URL', models.URLField(blank=True)),
                ('twitter_URL', models.URLField(blank=True)),
                ('married', models.BooleanField()),
                ('name_of_spouse', models.CharField(blank=True, max_length=750)),
                ('name_of_child', models.CharField(blank=True, max_length=750)),
                ('surname', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
