# Generated by Django 2.0.4 on 2018-04-15 22:31

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('active', models.BooleanField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Legislation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True)),
                ('authors', models.TextField()),
                ('chamber', models.TextField()),
                ('strategic_plan', models.TextField()),
                ('effective', models.DateField()),
                ('favorable', models.BooleanField()),
                ('is_law', models.BooleanField()),
                ('was_defeated', models.BooleanField()),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=250, null=True)),
                ('state', models.CharField(choices=[('ALABAMA', 'AL'), ('ALASKA', 'AK'), ('ARIZONA', 'AZ'), ('ARKANSAS', 'AR'), ('CALIFORNIA', 'CA'), ('COLORADO', 'CO'), ('CONNECTICUT', 'CT'), ('DELAWARE', 'DE'), ('FLORIDA', 'FL'), ('GEORGIA', 'GA'), ('HAWAII', 'HI'), ('IDAHO', 'ID'), ('ILLINOIS', 'IL'), ('INDIANA', 'IN'), ('IOWA', 'IA'), ('KANSAS', 'KS'), ('KENTUCKY', 'KY'), ('LOUISIANA', 'LA'), ('MAINE', 'ME'), ('MARYLAND', 'MD'), ('MASSACHUSETTS', 'MA'), ('MICHIGAN', 'MI'), ('MINNESOTA', 'MN'), ('MISSISSIPPI', 'MS'), ('MISSOURI', 'MO'), ('MONTANA', 'MT'), ('NEBRASKA', 'NE'), ('NEVADA', 'NV'), ('NEW_HAMPSHIRE', 'NH'), ('NEW_JERSEY', 'NJ'), ('NEW_MEXICO', 'NM'), ('NEW_YORK', 'NY'), ('NORTH_CAROLINA', 'NC'), ('NORTH_DAKOTA', 'ND'), ('OHIO', 'OH'), ('OKLAHOMA', 'OK'), ('OREGON', 'OR'), ('PENNSYLVANIA', 'PA'), ('RHODE_ISLAND', 'RI'), ('SOUTH_CAROLINA', 'SC'), ('SOUTH_DAKOTA', 'SD'), ('TENNESSEE', 'TN'), ('TEXAS', 'TX'), ('UTAH', 'UT'), ('VERMONT', 'VT'), ('VIRGINIA', 'VA'), ('WASHINGTON', 'WA'), ('WEST_VIRGINIA', 'WV'), ('WISCONSIN', 'WI'), ('WYOMING', 'WY'), ('AMERICAN_SAMOA', 'AS'), ('DISTRICT_OF_COLUMBIA', 'DC'), ('FEDERATED_STATES_OF_MICRONESIA', 'FM'), ('GUAM', 'GU'), ('MARSHALL_ISLANDS', 'MH'), ('NORTHERN_MARIANA_ISLANDS', 'MP'), ('PALAU', 'PW'), ('PUERTO_RICO', 'PR'), ('VIRGIN_ISLANDS', 'VI'), ('ARMED_FORCES_AMERICAS', 'AA'), ('ARMED_FORCES_AFRICA_CANADA_EUROPE_MIDDLE_EAST', 'AE'), ('ARMED_FORCES_PACIFIC', 'AP')], max_length=25, null=True)),
                ('zip_code', models.PositiveIntegerField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('fax_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('email_address', models.EmailField(blank=True, max_length=254, unique=True)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('DOCTOR', 'Dr.'), ('ESQUIRE', 'Esq.'), ('HONORABLE', 'Hon.'), ('JUNIOR', 'Jr.'), ('LADY', 'Lady'), ('LORD', 'Lord'), ('MISS', 'Miss'), ('MESDAMES', 'Mmes'), ('MISTER', 'Mr.'), ('MISSES', 'Mrs.'), ('MIZ', 'Ms.'), ('MONSIGNOR', 'Msgr.'), ('PROFESSOR', 'Prof.'), ('REVEREND', 'Rev.'), ('RIGHT_HONORABLE', 'Rt. Hon.'), ('SIR', 'Sir'), ('SENIOR', 'Sr.'), ('SAINT', 'St.')], max_length=7, null=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('middle_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=500, null=True)),
                ('suffix', models.CharField(choices=[('SENIOR', 'Sr.'), ('JUNIOR', 'Jr.'), ('SECOND', 'II'), ('THIRD', 'III'), ('FOURTH', 'IV')], max_length=3, null=True)),
                ('credentials', models.TextField()),
                ('specialty', models.TextField()),
                ('active', models.BooleanField()),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='legislation',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planned_parenthood.Location'),
        ),
    ]
