# Generated by Django 2.0.4 on 2018-04-16 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planned_parenthood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('DOCTOR', 'Dr.'), ('ESQUIRE', 'Esq.'), ('HONORABLE', 'Hon.'), ('JUNIOR', 'Jr.'), ('LADY', 'Lady'), ('LORD', 'Lord'), ('MISS', 'Miss'), ('MESDAMES', 'Mmes'), ('MISTER', 'Mr.'), ('MISSES', 'Mrs.'), ('MIZ', 'Ms.'), ('MONSIGNOR', 'Msgr.'), ('PROFESSOR', 'Prof.'), ('REVEREND', 'Rev.'), ('RIGHT_HONORABLE', 'Rt. Hon.'), ('SIR', 'Sir'), ('SENIOR', 'Sr.'), ('SAINT', 'St.')], max_length=7, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('middle_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=500, null=True)),
                ('suffix', models.CharField(choices=[('SENIOR', 'Sr.'), ('JUNIOR', 'Jr.'), ('SECOND', 'II'), ('THIRD', 'III'), ('FOURTH', 'IV')], max_length=3, null=True)),
                ('email_address', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('transaction', models.FloatField()),
                ('donation', models.BooleanField()),
                ('income', models.BooleanField()),
                ('investment', models.BooleanField()),
                ('expense', models.BooleanField()),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('internal_projects_worked_on', models.TextField()),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.RemoveField(
            model_name='location',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='location',
            name='fax_number',
        ),
        migrations.RemoveField(
            model_name='location',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='suffix',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='title',
        ),
        migrations.AddField(
            model_name='clinic',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planned_parenthood.Staff'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(choices=[('ALABAMA', 'AL'), ('ALASKA', 'AK'), ('ARIZONA', 'AZ'), ('ARKANSAS', 'AR'), ('CALIFORNIA', 'CA'), ('COLORADO', 'CO'), ('CONNECTICUT', 'CT'), ('DELAWARE', 'DE'), ('FLORIDA', 'FL'), ('GEORGIA', 'GA'), ('HAWAII', 'HI'), ('IDAHO', 'ID'), ('ILLINOIS', 'IL'), ('INDIANA', 'IN'), ('IOWA', 'IA'), ('KANSAS', 'KS'), ('KENTUCKY', 'KY'), ('LOUISIANA', 'LA'), ('MAINE', 'ME'), ('MARYLAND', 'MD'), ('MASSACHUSETTS', 'MA'), ('MICHIGAN', 'MI'), ('MINNESOTA', 'MN'), ('MISSISSIPPI', 'MS'), ('MISSOURI', 'MO'), ('MONTANA', 'MT'), ('NEBRASKA', 'NE'), ('NEVADA', 'NV'), ('NEW_HAMPSHIRE', 'NH'), ('NEW_JERSEY', 'NJ'), ('NEW_MEXICO', 'NM'), ('NEW_YORK', 'NY'), ('NORTH_CAROLINA', 'NC'), ('NORTH_DAKOTA', 'ND'), ('OHIO', 'OH'), ('OKLAHOMA', 'OK'), ('OREGON', 'OR'), ('PENNSYLVANIA', 'PA'), ('RHODE_ISLAND', 'RI'), ('SOUTH_CAROLINA', 'SC'), ('SOUTH_DAKOTA', 'SD'), ('TENNESSEE', 'TN'), ('TEXAS', 'TX'), ('UTAH', 'UT'), ('VERMONT', 'VT'), ('VIRGINIA', 'VA'), ('WASHINGTON', 'WA'), ('WEST_VIRGINIA', 'WV'), ('WISCONSIN', 'WI'), ('WYOMING', 'WY'), ('AMERICAN_SAMOA', 'AS'), ('DISTRICT_OF_COLUMBIA', 'DC'), ('FEDERATED_STATES_OF_MICRONESIA', 'FM'), ('GUAM', 'GU'), ('MARSHALL_ISLANDS', 'MH'), ('NORTHERN_MARIANA_ISLANDS', 'MP'), ('PALAU', 'PW'), ('PUERTO_RICO', 'PR'), ('VIRGIN_ISLANDS', 'VI'), ('ARMED_FORCES_AMERICAS', 'AA'), ('ARMED_FORCES_AFRICA_CANADA_EUROPE_MIDDLE_EAST', 'AE'), ('ARMED_FORCES_PACIFIC', 'AP')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planned_parenthood.Location'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planned_parenthood.Demographics'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='transactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planned_parenthood.Staff'),
        ),
        migrations.AddField(
            model_name='demographics',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planned_parenthood.Location'),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planned_parenthood.Demographics'),
        ),
    ]
